apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/app"   # Paki-Replace with the actual path on the Kubernetes node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bash-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bash-app
  template:
    metadata:
      labels:
        app: bash-app
    spec:
      containers:
      - name: bash-app-container
        image: maximolds/mini_project_test:v1   # Use the puushed Docker image
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: app-storage
            mountPath: /app/data   # Mount the volume where data is shared
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: bash-app-service
spec:
  selector:
    app: bash-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
