apiVersion: apps/v1
kind: Deployment
metadata:
  name: bash-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bash-app
  template:
    metadata:
      labels:
        app: bash-app
    spec:
      containers:
      - name: bash-app-container
        image: masterdocker05/shift-script:latest  # Use the puushed Docker image
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: app-storage
            mountPath: /app/data   # Mount the volume where data is shared
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-pvc
